### PR TITLE
docs: crop and optimize images

### PR DESCRIPTION
**Pull request by thaJeztah**
Cropped and optimized images.

### CODE REVIEW

**Comment by jessfraz** [comment]
you rule!!!

**Comment by jessfraz** [comment]
oh no sorry I had updated the PR can you rebase or I can

**Comment by jessfraz** [comment]
oh I know :)

**Comment by jessfraz** [comment]
dont worry :)

**Comment by thaJeztah** [comment]
ping @jfrazelle looks like I did _something_ wrong with branching 

ah! that's probably it. Hope you can :smile: not very good Git-fu :D

**Comment by thaJeztah** [comment]
I'll leave it as-is then; I (bit creatively) cropped the images to the (what I think) important bits. And repositioned things a bit there to make em smaller.

If you want them different, let me know. Have fun with 'em :)

**Comment by jessfraz** [comment]
no this is great :) thanks so much

On Wed, Apr 1, 2015 at 4:44 PM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> I'll leave it as-is then; I (bit creatively) cropped the images to the
> (what I think) important bits. And repositioned things a bit there to make
> em smaller.
> 
> If you want them different, let me know. Have fun with 'em :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jfrazelle/docker/pull/1#issuecomment-88664940.

## 

Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

**Comment by jessfraz** [comment]
closing because I cherry-picked :D

**Comment by thaJeztah** [comment]
Thanks! Left it open, just in case :smile:

**Pull request closed without merging**
